services:
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - docker_network

  server:
    container_name: server
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge

volumes:
  redis:
